export const TOSS_API_PATHS = {
  OAUTH_TOKEN: '/oauth2/token',
  PRICES: '/api/v1/prices',
  CANDLES: '/api/v1/candles',
  ACCOUNTS: '/api/v1/accounts',
  HOLDINGS: '/api/v1/holdings',
  STOCKS_ALL: '/api/v1/stocks/all',
  RANKINGS: '/api/v1/rankings',
  STOCK_INVESTOR_TRADING: (symbol: string) => `/api/v1/stocks/${encodeURIComponent(symbol)}/investor-trading`,
  MARKET_INDICATOR_PRICES: '/api/v1/market-indicators/prices',
  MARKET_INDICATOR_CANDLES: (symbol: string) =>
    `/api/v1/market-indicators/${encodeURIComponent(symbol)}/candles`,
  EXCHANGE_RATE: '/api/v1/exchange-rate',
  MARKET_CALENDAR_KR: '/api/v1/market-calendar/KR',
  ORDERBOOK: '/api/v1/orderbook',
  BUYING_POWER: '/api/v1/buying-power',
  SELLABLE_QUANTITY: '/api/v1/sellable-quantity',
  ORDERS: '/api/v1/orders',
  ORDER_MODIFY: (orderId: string) => `/api/v1/orders/${encodeURIComponent(orderId)}/modify`,
  ORDER_CANCEL: (orderId: string) => `/api/v1/orders/${encodeURIComponent(orderId)}/cancel`,
} as const;
